// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vixqjncuhhgdicrulxtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpeHFqbmN1aGhnZGljcnVseHR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTgyOTAsImV4cCI6MjA2MjQ3NDI5MH0.kW0qdQOcwpToSC9AbnLNkbxUQNqBCBWWDhiGzActLnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);